#configure defaults values using anchor and aliases
#auth:
        # username: biggaji
        # password: $DOCKER_PASSWORD
        
default: &default
  docker:
    - image: circleci/node:10-browsers
      
  
version: 2.1

jobs:
  build:
    <<: *default
  steps:
    - checkout
    - run:
        name: Output node version
        command: |
          echo "Hello world"
          node -v
