#configure defaults values using anchor and aliases
#auth:
        # username: biggaji
        # password: $DOCKER_PASSWORD
        
# default: &default
#   docker:
#     - image: circleci/node:10-browsers
      
  # Without orbs
# version: 2.1

# jobs:
#   build:
#     docker: 
#       - image: circleci/node:10-browsers
#     steps:
#       - checkout
#       - run:
#           name: Output node version
#           command: |
#             echo "Hello world"
#             node -v

# Using Orbs

version: 2.1

orbs:
  node: circleci/node@4.1.0

workflows:
  test:
    jobs:
      - node/test