	version: 2.1
	jobs:
		build:
			docker: #Executor
				- image: circleci/node:10-browsers
					auth:
						username: biggaji
						password: Adeyinka02
			steps:
				- checkout
				- run:
						name: Say Node version
						command: 
							node --version